const products=[
{id:1,name:'Relaxed Overshirt',cat:'Apparel',price:1499,old:1899,badge:'BESTSELLER',tone:'p1',image:'https://d29c1z66frfv6c.cloudfront.net/pub/media/catalog/product/large/51cdced9e9a35f3ca9d543e7d52301767772b628_xxl-1.jpg',desc:'An easy layer with a relaxed silhouette and softly structured finish. Made for everyday rotation.'},
{id:2,name:'Cloud Knit Tee',cat:'Apparel',price:899,old:null,badge:'NEW',tone:'p2',image:'https://www.axism.com/cdn/shop/products/1301-white-front.jpg?v=1758718354&width=600',desc:'Lightweight comfort with a clean, elevated shape. Your new everyday tee.'},
{id:3,name:'Studio Tote',cat:'Accessories',price:1299,old:1599,badge:'BESTSELLER',tone:'p3',image:'https://www.henristore.com.br/cdn/shop/files/banner-roupas.png?v=1766160477',desc:'A roomy carry-all designed to move from weekday commutes to weekend plans.'},
{id:4,name:'Everyday Cap',cat:'Accessories',price:699,old:null,badge:null,tone:'p4',image:'https://my-giftz.com/cdn/shop/collections/ChatGPT_Image_14_jun_2025_15_39_12.png?v=1749908380&width=2048',desc:'A minimal six-panel cap with an adjustable fit and understated Vibe mark.'},
{id:5,name:'Soft Form Hoodie',cat:'Apparel',price:1799,old:2199,badge:'NEW',tone:'p5',image:'https://debberies.nl/cdn/shop/articles/Photoroom_20251211_203358_c5f9661f-9cc3-4dbb-b5ef-082a0d07c503.png?v=1775631527',desc:'A premium-feel hoodie with a soft brushed interior and effortless oversized fit.'},
{id:6,name:'Daily Runner',cat:'Footwear',price:2499,old:2999,badge:'LIMITED',tone:'p6',image:'https://ogavzrkmyjkodedifddw.supabase.co/storage/v1/object/public/blog-images/blog-3.2/hero-1780247513972.webp',desc:'Light on your feet, easy on your eyes. Built for daily movement and city miles.'},
{id:7,name:'Ceramic Tumbler',cat:'Lifestyle',price:799,old:null,badge:null,tone:'p7',image:'https://www.potteryfortheplanet.com/cdn/shop/files/Pottery-For-The-Planet-Signature-Travel-Cups-Sandy-1_e397d48f-33b3-4b18-a70e-634a4e15fdea_grande.jpg?v=1720142018',desc:'A tactile ceramic tumbler for slow mornings, desk breaks and everything between.'},
{id:8,name:'Weekender Pack',cat:'Lifestyle',price:2199,old:2499,badge:'BESTSELLER',tone:'p8',image:'https://www.awaytravel.com/cdn/shop/files/PDP_Hero_Weekender_Black.png?v=1780505333&width=1000',desc:'A compact travel companion with smart storage and a clean, timeless profile.'}
];
let filter='All',query='',cart=[];
const grid=document.getElementById('productGrid'), cartDrawer=document.getElementById('cartDrawer'), overlay=document.getElementById('overlay');
function money(n){return '₹'+n.toLocaleString('en-IN')}
function render(){let list=products.filter(p=>(filter==='All'||p.cat===filter)&&p.name.toLowerCase().includes(query.toLowerCase()));const s=document.getElementById('sort').value;if(s==='low')list.sort((a,b)=>a.price-b.price);if(s==='high')list.sort((a,b)=>b.price-a.price);if(s==='name')list.sort((a,b)=>a.name.localeCompare(b.name));grid.innerHTML=list.length?list.map(p=>`<article class="product-card" data-id="${p.id}"><div class="product-image ${p.tone}" style="background-image:url('${p.image}')">${p.badge?`<span class="badge">${p.badge}</span>`:''}<button class="heart" data-heart="${p.id}" aria-label="Wishlist">♡</button></div><div class="product-info"><span class="category-name">${p.cat}</span><h3>${p.name}</h3><span class="price">${money(p.price)} ${p.old?`<span class="old">${money(p.old)}</span>`:''}</span></div></article>`).join(''):`<div class="empty-results"><h3>No pieces found.</h3><p>Try another search or category.</p></div>`}
function applyImageFallbacks(){
 document.querySelectorAll('.product-image[style],.cart-thumb[style],.modal-image[style]').forEach(el=>{
   if(el.dataset.bound)return;
   el.dataset.bound='1';
   el.addEventListener('error',()=>{el.style.backgroundImage='none';el.classList.add('image-fallback')},{once:true});
 });
}

function updateCart(){document.getElementById('cartCount').textContent=cart.reduce((n,x)=>n+x.qty,0);const items=document.getElementById('cartItems'),empty=document.getElementById('cartEmpty'),bottom=document.getElementById('cartBottom');if(!cart.length){items.innerHTML='';empty.style.display='block';bottom.style.display='none';return}empty.style.display='none';bottom.style.display='block';items.innerHTML=cart.map(x=>{const p=products.find(p=>p.id===x.id);return `<div class="cart-row"><div class="cart-thumb ${p.tone}" style="background-image:url('${p.image}')"></div><div><h4>${p.name}</h4><small>${money(p.price)}</small><div class="qty"><button data-dec="${p.id}">−</button><span>${x.qty}</span><button data-inc="${p.id}">+</button></div></div><strong>${money(p.price*x.qty)}</strong></div>`}).join('');document.getElementById('subtotal').textContent=money(cart.reduce((n,x)=>n+products.find(p=>p.id===x.id).price*x.qty,0))}
function openCart(){cartDrawer.classList.add('open');overlay.classList.add('show');document.body.style.overflow='hidden'}function closeOverlays(){cartDrawer.classList.remove('open');overlay.classList.remove('show');document.getElementById('productModal').classList.remove('show');document.body.style.overflow=''}
function add(id){const found=cart.find(x=>x.id===id);found?found.qty++:cart.push({id,qty:1});updateCart();openCart();toast()}
function toast(){const t=document.getElementById('toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)}
function showProduct(id){const p=products.find(p=>p.id===id);document.getElementById('modalContent').innerHTML=`<div class="modal-product"><div class="modal-image ${p.tone}" style="background-image:url('${p.image}')"></div><div class="modal-copy"><span class="eyebrow">${p.cat.toUpperCase()}</span><h2>${p.name}</h2><div class="price">${money(p.price)} ${p.old?`<span class="old">${money(p.old)}</span>`:''}</div><p>${p.desc}</p><button class="primary" id="modalAdd">Add to bag <span>→</span></button></div></div>`;document.getElementById('modalAdd').onclick=()=>add(p.id);document.getElementById('productModal').classList.add('show');overlay.classList.add('show');document.body.style.overflow='hidden'}
grid.addEventListener('click',e=>{const heart=e.target.closest('[data-heart]');if(heart){heart.textContent=heart.textContent==='♡'?'♥':'♡';return}const card=e.target.closest('.product-card');if(card)showProduct(+card.dataset.id)});
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render();applyImageFallbacks();document.getElementById('shop').scrollIntoView({behavior:'smooth',block:'start'})});
document.querySelectorAll('.category').forEach(b=>b.onclick=()=>{filter=b.dataset.cat;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===filter));render();applyImageFallbacks();document.getElementById('shop').scrollIntoView({behavior:'smooth'})});
document.getElementById('sort').onchange=()=>{render();applyImageFallbacks()};document.getElementById('searchInput').oninput=e=>{query=e.target.value;render();applyImageFallbacks()};document.querySelector('.search-toggle').onclick=()=>{document.getElementById('searchbar').classList.toggle('open');if(document.getElementById('searchbar').classList.contains('open'))document.getElementById('searchInput').focus()};document.getElementById('clearSearch').onclick=()=>{document.getElementById('searchInput').value='';query='';render()};document.querySelector('.cart-toggle').onclick=openCart;document.getElementById('closeCart').onclick=closeOverlays;document.querySelector('.modal-close').onclick=closeOverlays;overlay.onclick=closeOverlays;document.getElementById('startShopping').onclick=closeOverlays;
document.getElementById('cartItems').addEventListener('click',e=>{const inc=e.target.closest('[data-inc]'),dec=e.target.closest('[data-dec]');if(inc){const x=cart.find(x=>x.id==inc.dataset.inc);x.qty++}if(dec){const x=cart.find(x=>x.id==dec.dataset.dec);x.qty--;if(x.qty<=0)cart=cart.filter(y=>y!==x)}updateCart()});
document.getElementById('newsletterForm').onsubmit=e=>{e.preventDefault();e.target.innerHTML='<strong style="padding:12px 18px;font-size:12px">You’re on the list ✦</strong>'};document.querySelector('.checkout').onclick=()=>toast();render();applyImageFallbacks();updateCart();
